name: 'random'
description: 'Print random number'
inputs:
  my-prefix:
    description: 'Prefix'
    required: true
    default: ''
outputs:
  my-random:
    description: 'Random number'
    value: ${{steps.return-result.outputs.some-random}}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.my-prefix}}
branding:
  icon: 'archive'
  color: 'gray-dark'