name: 'random'
description: 'Print random number'
inputs:
  my-prefix:
    description: 'Prefix'
    required: true
    default: ''
outputs:
  my-random:
    description: 'Random number'
    value: ${{steps.return-result.outputs.some-random}}
runs:
  using: 'composite'
  steps:
    - name: Print 
      run: |
        echo Args: ${{ inputs.my-prefix }}
      shell: bash
    - id: return-result 
      run: | 
        echo "some-random=`echo ${{ inputs.my-prefix }} $RANDOM`" >> $GITHUB_OUTPUT
      shell: bash
branding:
  icon: 'archive'
  color: 'gray-dark'