name: 'random'
description: 'Print random number'
inputs:
  to-count:
    description: 'Args to count'
    required: true
    default: ''
outputs:
  my-arg-count:
    description: 'The total'
    value: ${{steps.return-result.outputs.num-count}}
runs:
  using: 'composite'
  steps:
    - name: Print args 
      run: |
        echo Args: ${{ inputs.to-count }}
      shell: bash
    - id: return-result 
      run: | 
        echo "num-count=`${{ github.action_path }}/count-args.sh ${{ inputs.to-count }}`" >> $GITHUB_OUTPUT
      shell: bash
branding:
  icon: 'archive'
  color: 'gray-dark'